"""L2-05 崩溃安全层 · 公共导出."""
from app.l1_09.crash_safety.appender import append_atomic
from app.l1_09.crash_safety.atomic_writer import write_atomic
from app.l1_09.crash_safety.canonical_json import canonical_json_without_hash
from app.l1_09.crash_safety.hash_chain import (
    GENESIS_HASH,
    compute_hash_chain_link,
    verify_chain_link,
)
from app.l1_09.crash_safety.schemas import (
    MAX_SNAPSHOT_SIZE_BYTES,
    PIPE_BUF_LIMIT,
    RETRY_BACKOFF_MS,
    RETRY_MAX,
    TMP_ORPHAN_AGE_HOURS,
    AppendResult,
    ChecksumMismatch,
    CrashSafetyError,
    DiskFullError,
    FilesystemReadOnly,
    FsyncFailed,
    HashChainLink,
    HashMismatchError,
    IntegrityMethod,
    IntegrityReport,
    IntegrityState,
    InvalidArgumentError,
    IOErrorCS,
    LineTooLargeError,
    OrphanTmpError,
    PartialWriteError,
    PathError,
    PermissionError,
    RecoveryAction,
    RecoveryActionKind,
    RenameFailed,
    WriteMethod,
    WriteResult,
)

__all__ = [
    "append_atomic",
    "canonical_json_without_hash",
    "compute_hash_chain_link",
    "verify_chain_link",
    "write_atomic",
    "GENESIS_HASH",
    "MAX_SNAPSHOT_SIZE_BYTES",
    "PIPE_BUF_LIMIT",
    "RETRY_BACKOFF_MS",
    "RETRY_MAX",
    "TMP_ORPHAN_AGE_HOURS",
    "AppendResult",
    "ChecksumMismatch",
    "CrashSafetyError",
    "DiskFullError",
    "FilesystemReadOnly",
    "FsyncFailed",
    "HashChainLink",
    "HashMismatchError",
    "IntegrityMethod",
    "IntegrityReport",
    "IntegrityState",
    "InvalidArgumentError",
    "IOErrorCS",
    "LineTooLargeError",
    "OrphanTmpError",
    "PartialWriteError",
    "PathError",
    "PermissionError",
    "RecoveryAction",
    "RecoveryActionKind",
    "RenameFailed",
    "WriteMethod",
    "WriteResult",
]
